# Generated by Django 5.1.1 on 2024-10-03 21:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('movies_orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='orders',
            field=models.ManyToManyField(related_name='movie_orders', through='movies_orders.MovieOrder', to=settings.AUTH_USER_MODEL),
        ),
    ]
